disabled_rules:
- type_name
- force_cast
- force_try
- trailing_comma
- nesting
- large_tuple
- cyclomatic_complexity
- identifier_name
- line_length
- file_length
- function_body_length
- opening_brace
